# Application YAML configuration
spring:

  # Enable h2 console
  h2:
    console:
      enabled: true
      path: /console

  # Set-up datasource
  datasource:
    url: jdbc:h2:mem:monodb
    driverClassName: org.h2.Driver
    username: admin
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
